[workspace]
members = ["mpc_derive"]

[workspace.lints.rust]
missing_docs = "warn"
elided_lifetimes_in_paths = "warn"
unsafe_code = "deny" # Only used in the array module

[package]
name = "mpc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
mpc_derive.path = "mpc_derive"
