[workspace]
members = ["rmpc_derive"]

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny" # Only used in the array module

[package]
name = "rmpc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
libm = "0.2.15"
rmpc_derive.path = "rmpc_derive"

[profile.dev]
opt-level = 1

[dev-dependencies]
macroquad = "0.4.14"
